import { describe, it, expect } from 'vitest';
import { execFileSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { join, resolve } from 'path';

/**
 * The `needs-info` re-check automation (issue #680) fires on every
 * `issue_comment.created` while an issue carries `needs-info`. Its own comment
 * satisfies that condition and it posts under the same account as the
 * reporter, so it re-arms itself: #678 got 11 back-to-back re-checks with no
 * reporter input, each a full LLM conversation.
 *
 * `.github/scripts/automation-loop-guard.py` is the repo-side guard. The
 * automation definition lives outside git, so this test is the only thing that
 * can pin the rule that breaks the cycle. It fails whenever the guard is
 * missing or stops suppressing an automation's own comment — the exact
 * regression that reopened #680.
 */
const REPO_ROOT = resolve(__dirname, '..', '..', '..', '..');
const SCRIPT = join(REPO_ROOT, '.github', 'scripts', 'automation-loop-guard.py');
const FIXTURE = join(
  REPO_ROOT,
  'apps',
  'api',
  'src',
  'utils',
  '__fixtures__',
  'needs-info-automation-comments.json'
);

/** The mandated marker every automated comment carries (automation-loop-guard.py). */
const AI_FOOTER =
  'This comment was created by an AI agent (OpenHands) on behalf of the repository maintainers.';

interface Comment {
  id: number;
  body: string;
  user: { login: string; type: string };
}

interface Fixture {
  source: string;
  issue: number;
  needsInfo: boolean;
  comments: Comment[];
}

function decide(needsInfo: boolean, comment: Comment): string {
  const payload = JSON.stringify({
    action: 'created',
    issue: { number: 680, labels: needsInfo ? [{ name: 'needs-info' }] : [{ name: 'chore' }] },
    comment,
  });
  return execFileSync('python3', [SCRIPT, 'decide', '-'], {
    input: payload,
    encoding: 'utf8',
  }).trim();
}

function reporterBody(text: string): string {
  return `${text}\n\n---\n*This comment was created by an AI agent (OpenHands) on behalf of the repository maintainers.*`;
}

describe('automation-loop-guard.py', () => {
  it('exists — without it the #680 loop cannot be reproduced or guarded', () => {
    expect(existsSync(SCRIPT)).toBe(true);
  });

  it('pins the disclosure marker it suppresses on', () => {
    // If this wording changes, the guard stops recognising the automation's
    // own comments and #680's loop returns. Pin it to the script itself.
    expect(readFileSync(SCRIPT, 'utf8')).toContain(AI_FOOTER);
  });

  it('prints the clause the deploy script applies to the backend filter', () => {
    // `deploy-automation-loop-guard.py` reads this clause and PATCHes it onto
    // the live automations; a JMESPath filter cannot call the script, so this
    // string IS the deployed guard. Pin it.
    const clause = execFileSync('python3', [SCRIPT, 'guard-clause'], { encoding: 'utf8' }).trim();
    expect(clause).toBe("!icontains(comment.body, 'AI agent (OpenHands)')");
  });

  it('suppresses the automation acting on its own comment', () => {
    // The exact shape of #678: a re-check comment is the trigger for the next.
    const own: Comment = {
      id: 6033790503,
      body: reporterBody('**Needs-info re-check — no reporter reply**'),
      user: { login: 'adminypc', type: 'User' },
    };
    expect(decide(true, own)).toBe('act=no reason=self-trigger');
  });

  it('suppresses every real footer variant the automation emits', () => {
    // The automation is not consistent: on #680 it ended its own comments with
    // "created … maintainers", "generated … maintainers" and "created …
    // owner". A guard that matches only the canonical sentence lets two of
    // three through and the loop continues.
    const variants: string[] = [
      'This comment was created by an AI agent (OpenHands) on behalf of the repository maintainers.',
      'This comment was generated by an AI agent (OpenHands) on behalf of the repository maintainers.',
      'This comment was created by an AI agent (OpenHands) on behalf of the repository owner.',
    ];
    for (const footer of variants) {
      const own: Comment = {
        id: 0,
        body: `Automated re-check.\n\n_${footer}_`,
        user: { login: 'adminypc', type: 'User' },
      };
      expect(decide(true, own), footer).toBe('act=no reason=self-trigger');
    }
  });

  it('acts on a reporter reply that quotes an automated footer', () => {
    // Reported by devin review on #683: a reporter answering the request may
    // quote the prior automated comment, footer and all. The quote is not the
    // reply's own footer — the re-check must run.
    const reply: Comment = {
      id: 9,
      body: [
        'Here is the requested log.',
        '> This comment was created by an AI agent (OpenHands) on behalf of the repository maintainers.',
      ].join('\n'),
      user: { login: 'adminypc', type: 'User' },
    };
    expect(decide(true, reply)).toBe('act=yes reason=reporter-reply');
  });

  it('acts on a genuine reporter reply while needs-info is present', () => {
    const reply: Comment = {
      id: 1,
      body: 'It is a throwaway fixture, please close it.',
      user: { login: 'adminypc', type: 'User' },
    };
    expect(decide(true, reply)).toBe('act=yes reason=reporter-reply');
  });

  it('does not act when the issue no longer carries needs-info', () => {
    const reply: Comment = {
      id: 2,
      body: 'some reply',
      user: { login: 'adminypc', type: 'User' },
    };
    expect(decide(false, reply)).toBe('act=no reason=not-needs-info');
  });

  it('treats an AI comment on an issue without needs-info as not-needed', () => {
    const own: Comment = {
      id: 3,
      body: reporterBody('anything'),
      user: { login: 'adminypc', type: 'User' },
    };
    expect(decide(false, own)).toBe('act=no reason=not-needs-info');
  });

  it('replays the real #680 stream and shows the guard ends the loop', () => {
    // Verbatim bodies of the automation's own comments on #680, captured from
    // the GitHub API (the fixture records its source). Every one is the
    // automation's; a plain filter fires on all of them, the guard on none.
    // Using the real bodies — not generated ones — is what lets this test see
    // a footer change the automation actually ships: #680 already carried two
    // wordings the canonical sentence misses.
    const fixture: Fixture = JSON.parse(readFileSync(FIXTURE, 'utf8'));
    expect(fixture.comments.length).toBeGreaterThan(0);
    expect(new Set(fixture.comments.map((c) => c.user.login))).toEqual(new Set(['adminypc']));
    // The fixture must keep exercising the drift; if it is ever reduced to one
    // canonical footer, this test stops guarding the variant bug.
    expect(fixture.comments.some((c) => c.body.includes('repository owner'))).toBe(true);
    expect(fixture.comments.some((c) => c.body.includes('was generated by an AI agent'))).toBe(
      true
    );

    const out = execFileSync('python3', [SCRIPT, 'replay', '-'], {
      input: JSON.stringify({ needsInfo: fixture.needsInfo, comments: fixture.comments }),
      encoding: 'utf8',
    });
    // The unguarded filter (any comment while needs-info) fires on every one;
    // the guard fires on none, because every one is the automation's own.
    expect(out).toContain(`runs_old=${fixture.comments.length}`);
    expect(out).toContain('runs_guarded=0');
  });
});
