import { describe, expect, it } from "vitest";
import fs from "fs";
import path from "path";
import { matchesDynamicPattern } from "./lib/dynamic-routes";

/**
 * The visual sweep can only capture a dynamic page if `dynamic-routes.json`
 * names a concrete URL for its pattern. That map is generated by
 * `resolve-dynamic-routes.ts`, which used to overwrite itself with only the
 * patterns it managed to resolve in a given run — so a pattern the resolver
 * could not reach silently vanished from the file, and its pages dropped out of
 * the gallery. Counseling and inventory detail/edit screens did exactly that.
 *
 * This guard makes the contract explicit and machine-checked:
 *  - every dynamic `page.tsx` pattern is either resolved in the map or listed,
 *    with a reason, in `dynamic-routes.unresolved.json`;
 *  - every map entry names a real pattern, and its URL path matches it;
 *  - nothing stale is left in either file.
 *
 * The allowlist is a backlog, like `dead-links.test.ts`'s `KNOWN_MISSING`: it
 * may shrink, never grow silently. Add a pattern to it only when the seed holds
 * no row the resolver could read.
 */

const SCRIPTS_DIR = __dirname;
const APP_DIR = path.join(SCRIPTS_DIR, "..", "src", "app");

interface UnresolvedEntry {
  reason: string;
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name === "page.tsx") out.push(full);
  }
  return out;
}

function routeFromFile(file: string): string {
  const rel = path.relative(APP_DIR, file).replace(/\/?page\.tsx$/, "");
  const cleaned = rel.replace(/\(([^)]*)\)/g, "").replace(/\/+/g, "/");
  const route = "/" + cleaned.replace(/^\/|\/$/g, "");
  return route === "/" ? "/" : route;
}

const patterns = walk(APP_DIR)
  .map(routeFromFile)
  .filter((r) => r.includes("["))
  .sort();

const resolved = JSON.parse(
  fs.readFileSync(path.join(SCRIPTS_DIR, "dynamic-routes.json"), "utf8"),
) as Record<string, string>;

const unresolved = JSON.parse(
  fs.readFileSync(
    path.join(SCRIPTS_DIR, "dynamic-routes.unresolved.json"),
    "utf8",
  ),
) as Record<string, UnresolvedEntry>;

describe("dynamic route coverage", () => {
  it("finds the app's dynamic patterns", () => {
    expect(patterns.length).toBeGreaterThan(50);
  });

  it("resolves or consciously allowlists every dynamic pattern", () => {
    const covered = new Set([
      ...Object.keys(resolved),
      ...Object.keys(unresolved),
    ]);
    const missing = patterns.filter((p) => !covered.has(p));
    expect(
      missing,
      `dynamic patterns with no URL in dynamic-routes.json and no entry in ` +
        `dynamic-routes.unresolved.json — the sweep cannot reach these pages:\n` +
        missing.map((m) => "  " + m).join("\n"),
    ).toEqual([]);
  });

  it("does not carry a route that no longer exists", () => {
    const known = new Set(patterns);
    expect(Object.keys(resolved).filter((k) => !known.has(k))).toEqual([]);
    expect(Object.keys(unresolved).filter((k) => !known.has(k))).toEqual([]);
  });

  it("does not resolve and allowlist the same pattern", () => {
    const both = Object.keys(resolved).filter((k) => k in unresolved);
    expect(
      both,
      "resolved patterns must be removed from the allowlist",
    ).toEqual([]);
  });

  it("gives every resolved URL a path that matches its pattern", () => {
    const bad: string[] = [];
    for (const [pattern, url] of Object.entries(resolved)) {
      const pathname = url.split("?")[0];
      if (!matchesDynamicPattern(pathname, pattern)) {
        bad.push(`${pattern} -> ${url}`);
      }
    }
    expect(bad).toEqual([]);
  });

  it("gives every allowlisted pattern a reason", () => {
    const thin = Object.entries(unresolved)
      .filter(([, v]) => !v?.reason || v.reason.trim().length < 10)
      .map(([k]) => k);
    expect(thin).toEqual([]);
  });

  it("marks the fixed-slug public pages as not probeable", () => {
    // `/unit/[slug]` and `/berita/[slug]` render from static content
    // (`educationUnits`, `content.ts`), not from the API list the resolver
    // fetches. Their slug must therefore not be probed for liveness: an empty
    // `/units` or `/marketing/campaigns` would otherwise fail a page that still
    // renders. This pins the `liveness: false` the resolver relies on.
    const src = fs.readFileSync(
      path.join(SCRIPTS_DIR, "resolve-dynamic-routes.ts"),
      "utf8",
    );
    for (const pattern of ["/unit/[slug]", "/berita/[slug]"]) {
      const block = src.slice(src.indexOf(`"${pattern}"`));
      const hint = block.slice(0, block.indexOf("},") + 1);
      expect(
        /liveness:\s*false/.test(hint),
        `${pattern} must set liveness: false so its static slug is not probed`,
      ).toBe(true);
    }
  });
});
