/**
 * E-Sign suspension lock — real PostgreSQL concurrency.
 *
 * The signed-lockout race is invisible to a mocked Prisma: a mock `$queryRaw`
 * returns whatever the test says, and a mock `$transaction` shares one object,
 * so it can never prove that a suspension which commits *after* the pre-flight
 * `assertCanSign` but *before* the final write is actually refused.
 *
 * This suite runs the real `EsignService` against a real PostgreSQL with the
 * real migrations, over independent pooled connections, so the advisory lock,
 * the `FOR UPDATE` re-read and the conditional writes have to do their work:
 *
 *  1. `signLetter` passes its pre-flight key read, a suspension commits, and the
 *     final transaction refuses — no signature, no SIGNED letter.
 *  2. `revokeLetterSignature` under the same interleaving writes no revocation.
 *  3. `changePassphrase` passes its pre-flight read, a suspension commits, and
 *     the swap neither clears the sentinel nor reports success.
 *  4. The suspension holds the key row lock and commits the sentinel; the
 *     signing transaction's `FOR UPDATE` re-read sees it and refuses.
 *  5. Normal signing with no suspension still works.
 *  6. A failed passphrase attempt cannot overwrite the sentinel with a
 *     short-lived lockout.
 *
 * Opt-in via RUN_DB_TESTS=1.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach, vi } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { Client } from 'pg';
import bcrypt from 'bcryptjs';
import { createKeyMaterial } from '@/utils/esign';

const MIGRATIONS = join(__dirname, '../../prisma/migrations');
const SENTINEL = '2099-01-01T00:00:00Z';
const PASS = 'passphrase-tanda-tangan-2026';
const NEW_PASS = 'passphrase-baru-2026';
const ACCOUNT_PASSWORD = 'password-akun-2026';

vi.mock('@/lib/redis', () => ({
  redis: {
    get: vi.fn().mockResolvedValue(null),
    set: vi.fn().mockResolvedValue('OK'),
    del: vi.fn().mockResolvedValue(1),
    setex: vi.fn().mockResolvedValue('OK'),
  },
}));

const describeDb = process.env.RUN_DB_TESTS ? describe : describe.skip;

vi.setConfig({ testTimeout: 120_000, hookTimeout: 180_000 });

function seed(keyMaterial: ReturnType<typeof createKeyMaterial>): string {
  const passwordHash = bcrypt.hashSync(ACCOUNT_PASSWORD, 4);
  return `
INSERT INTO units (id, name, type, address, updated_at) VALUES
  ('unit-1', 'SMA Qur''an Cipansor', 'SMA_QURAN', 'Cipansor', now());

INSERT INTO users (id, name, email, password_hash, is_active, updated_at) VALUES
  ('u-pengawas', 'Pengawas', 'pengawas@example.com', NULL, true, now()),
  ('u-ketua',    'Ketua',    'ketua@example.com',    '${passwordHash}', true, now()),
  ('u-enroll',   'Enrollee', 'enroll@example.com',   '${passwordHash}', true, now());

-- An approved ENROLLMENT request, awaiting passphrase activation.
INSERT INTO signing_key_requests
  (id, user_id, kind, status, decided_by_id, decided_at, granted_days, updated_at)
VALUES
  ('req-enroll', 'u-enroll', 'ENROLLMENT', 'APPROVED', 'u-pengawas', now(), 365, now());

INSERT INTO roles (id, code, name, realm, permissions, updated_at) VALUES
  ('role-pengawas', 'YAYASAN_PENGAWAS', 'Pengawas Yayasan', 'YAYASAN', '[]'::jsonb, now()),
  ('role-ketua', 'YAYASAN_KETUA', 'Ketua Yayasan', 'YAYASAN', '[]'::jsonb, now());

INSERT INTO user_role_assignments (id, user_id, role_id, is_primary, is_active, updated_at) VALUES
  ('a-ketua', 'u-ketua', 'role-ketua', true, true, now());

-- Real key material, generated by the same helper the service uses, so the
-- signing path runs the real crypto.
INSERT INTO user_signing_keys
  (id, user_id, algorithm, public_key, encrypted_private_key, kdf_salt, kdf_params, iv, auth_tag,
   failed_attempts, approved_at, expires_at, updated_at)
VALUES
  ('key-ketua', 'u-ketua', '${keyMaterial.algorithm}', '${keyMaterial.publicKey}',
   '${keyMaterial.encryptedPrivateKey}', '${keyMaterial.kdfSalt}',
   '${JSON.stringify(keyMaterial.kdfParams)}'::jsonb, '${keyMaterial.iv}', '${keyMaterial.authTag}',
   0, now(), now() + interval '365 days', now());

INSERT INTO letters
  (id, unit_id, direction, type, date, subject, content, nature, status, created_by_id, letter_number, updated_at)
VALUES
  ('letter-sign', 'unit-1', 'OUTGOING', 'SURAT_KETERANGAN', CURRENT_DATE, 'Keterangan',
   'Isi surat uji.', 'PUBLIC', 'READY_TO_SIGN', 'u-ketua', '001/SK/2026', now()),
  ('letter-revoke', 'unit-1', 'OUTGOING', 'SURAT_KETERANGAN', CURRENT_DATE, 'Keterangan',
   'Isi surat uji.', 'PUBLIC', 'SIGNED', 'u-ketua', '002/SK/2026', now());

INSERT INTO letter_reviewers (id, letter_id, reviewer_id, "order", status, is_signer) VALUES
  ('rev-1', 'letter-sign', 'u-ketua', 1, 'PENDING', true);

INSERT INTO letter_signatures
  (id, letter_id, signer_id, algorithm, public_key, digest, signature, verification_token, signed_at, signer_role_code)
VALUES
  ('sig-1', 'letter-revoke', 'u-ketua', 'Ed25519', 'pub', 'digest', 'sig', 'tok-1', now(), 'YAYASAN_KETUA');
`;
}

async function withClient<T>(url: string, fn: (db: Client) => Promise<T>): Promise<T> {
  const db = new Client({ connectionString: url });
  await db.connect();
  try {
    return await fn(db);
  } finally {
    await db.end();
  }
}

describeDb('esign suspension race (real PostgreSQL)', () => {
  const dbName = `cipansor_esign_race_${Date.now()}`;
  const baseUrl =
    process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5432/postgres';
  const targetUrl = (() => {
    const u = new URL(baseUrl);
    u.pathname = `/${dbName}`;
    return u.toString();
  })();

  let admin: Client;

  async function resetState(): Promise<void> {
    await withClient(targetUrl, async (db) => {
      await db.query(`DELETE FROM letter_signed_documents`);
      await db.query(`DELETE FROM letter_flow_events`);
      await db.query(`DELETE FROM letter_signatures WHERE id <> 'sig-1'`);
      await db.query(
        `UPDATE letter_signatures
         SET revoked_at = NULL, revoked_reason = NULL, revoked_by_id = NULL,
             revoked_by_role_code = NULL, revocation_digest = NULL,
             revocation_signature = NULL, revocation_public_key = NULL
         WHERE id = 'sig-1'`
      );
      await db.query(`UPDATE letters SET status = 'READY_TO_SIGN' WHERE id = 'letter-sign'`);
      await db.query(`UPDATE letters SET status = 'SIGNED' WHERE id = 'letter-revoke'`);
      await db.query(
        `UPDATE user_signing_keys SET locked_until = NULL, failed_attempts = 0 WHERE id = 'key-ketua'`
      );
      // The activation subject: ensure no stray key and a live approved request.
      await db.query(`DELETE FROM user_signing_keys WHERE user_id = 'u-enroll'`);
      await db.query(`UPDATE users SET is_active = true, deleted_at = NULL WHERE id = 'u-enroll'`);
      await db.query(`DELETE FROM board_member_suspensions WHERE user_id = 'u-enroll'`);
      await db.query(
        `UPDATE signing_key_requests
         SET status = 'APPROVED', decided_by_id = 'u-pengawas', decided_at = now(), granted_days = 365
         WHERE id = 'req-enroll'`
      );
    });
  }

  beforeAll(async () => {
    admin = new Client({ connectionString: baseUrl });
    await admin.connect();
    await admin.query(`CREATE DATABASE "${dbName}"`);
    const keyMaterial = createKeyMaterial(PASS);

    await withClient(targetUrl, async (db) => {
      const dirs = readdirSync(MIGRATIONS)
        .filter((d) => d !== 'migration_lock.toml')
        .sort();
      for (const dir of dirs) {
        await db.query(readFileSync(join(MIGRATIONS, dir, 'migration.sql'), 'utf8'));
      }
      await db.query(seed(keyMaterial));
    });
  }, 180_000);

  afterAll(async () => {
    if (admin) {
      await admin.query(`DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE)`);
      await admin.end();
    }
  });

  beforeEach(() => {
    vi.restoreAllMocks();
  });

  /** Load the service so its `prisma` singleton binds this throwaway DB. */
  async function loadModules() {
    const previousUrl = process.env.DATABASE_URL;
    process.env.DATABASE_URL = targetUrl;
    vi.resetModules();
    const esign = await import('../../src/modules/esign/esign.service');
    const prismaModule = await import('@/lib/prisma');
    return { EsignService: esign.EsignService, prisma: prismaModule.prisma, previousUrl };
  }

  async function unloadModules(previousUrl: string | undefined) {
    process.env.DATABASE_URL = previousUrl;
    vi.resetModules();
  }

  /**
   * Commit the suspension sentinel on a separate connection, exactly as
   * `BoardSuspensionService` writes it.
   */
  async function commitSuspensionLock(): Promise<void> {
    await withClient(targetUrl, async (db) => {
      await db.query(
        `UPDATE user_signing_keys SET locked_until = '${SENTINEL}' WHERE id = 'key-ketua'`
      );
    });
  }

  it('signLetter passes pre-flight, suspension commits, and no signature is written', async () => {
    await resetState();
    const { EsignService, prisma, previousUrl } = await loadModules();
    try {
      // The pre-flight key read returns a signable key, then the suspension
      // commits — deterministically between that read and the final transaction.
      const original = prisma.userSigningKey.findUnique.bind(prisma.userSigningKey);
      let first = true;
      vi.spyOn(prisma.userSigningKey, 'findUnique').mockImplementation((async (args: any) => {
        const result = await original(args);
        if (first) {
          first = false;
          await commitSuspensionLock();
        }
        return result;
      }) as any);

      await expect(EsignService.signLetter('letter-sign', 'u-ketua', PASS)).rejects.toThrow(
        /dibekukan|Pembekuan/i
      );

      await withClient(targetUrl, async (db) => {
        const sigs = await db.query(
          `SELECT count(*)::int AS n FROM letter_signatures WHERE letter_id = 'letter-sign'`
        );
        expect(sigs.rows[0].n, 'no signature may be minted for a suspended officer').toBe(0);
        const letter = await db.query(`SELECT status FROM letters WHERE id = 'letter-sign'`);
        expect(letter.rows[0].status, 'the letter must not become SIGNED').toBe('READY_TO_SIGN');
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('revokeLetterSignature under the same interleaving writes no revocation', async () => {
    await resetState();
    const { EsignService, prisma, previousUrl } = await loadModules();
    try {
      const original = prisma.userSigningKey.findUnique.bind(prisma.userSigningKey);
      let first = true;
      vi.spyOn(prisma.userSigningKey, 'findUnique').mockImplementation((async (args: any) => {
        const result = await original(args);
        if (first) {
          first = false;
          await commitSuspensionLock();
        }
        return result;
      }) as any);

      await expect(
        EsignService.revokeLetterSignature(
          'letter-revoke',
          { id: 'u-ketua', roleCode: 'YAYASAN_KETUA' },
          'Nomor surat ganda, diterbitkan ulang',
          PASS
        )
      ).rejects.toThrow(/dibekukan|Pembekuan/i);

      await withClient(targetUrl, async (db) => {
        const sig = await db.query(`SELECT revoked_at FROM letter_signatures WHERE id = 'sig-1'`);
        expect(sig.rows[0].revoked_at, 'no revocation may be written').toBeNull();
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('changePassphrase races a suspension, keeps the sentinel, and does not report success', async () => {
    await resetState();
    const { EsignService, prisma, previousUrl } = await loadModules();
    try {
      const original = prisma.userSigningKey.findUnique.bind(prisma.userSigningKey);
      let first = true;
      vi.spyOn(prisma.userSigningKey, 'findUnique').mockImplementation((async (args: any) => {
        const result = await original(args);
        if (first) {
          first = false;
          await commitSuspensionLock();
        }
        return result;
      }) as any);

      await expect(
        EsignService.changePassphrase('u-ketua', PASS, ACCOUNT_PASSWORD, NEW_PASS)
      ).rejects.toThrow(/dibekukan|Pembekuan|berubah/i);

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT locked_until FROM user_signing_keys WHERE id = 'key-ketua'`
        );
        expect(
          new Date(key.rows[0].locked_until).toISOString(),
          'the suspension sentinel must survive the passphrase swap'
        ).toBe(new Date(SENTINEL).toISOString());
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('signLetter fails closed when the suspension holds the key lock and commits the sentinel', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    const blocker = new Client({ connectionString: targetUrl });
    await blocker.connect();
    try {
      await blocker.query('BEGIN');
      await blocker.query(`SELECT id FROM "user_signing_keys" WHERE id = 'key-ketua' FOR UPDATE`);

      const pending = EsignService.signLetter('letter-sign', 'u-ketua', PASS);
      // Let the signer pass the pre-flight read and block on its key lock.
      await new Promise((resolve) => setTimeout(resolve, 500));
      await blocker.query(
        `UPDATE user_signing_keys SET locked_until = '${SENTINEL}' WHERE id = 'key-ketua'`
      );
      await blocker.query('COMMIT');

      await expect(pending).rejects.toThrow(/dibekukan|Pembekuan/i);

      await withClient(targetUrl, async (db) => {
        const sigs = await db.query(
          `SELECT count(*)::int AS n FROM letter_signatures WHERE letter_id = 'letter-sign'`
        );
        expect(sigs.rows[0].n).toBe(0);
      });
    } finally {
      await blocker.end();
      await unloadModules(previousUrl);
    }
  });

  it('normal signing with no suspension still works', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      const out = await EsignService.signLetter('letter-sign', 'u-ketua', PASS);
      expect(out.verificationToken).toBeTruthy();

      await withClient(targetUrl, async (db) => {
        const letter = await db.query(`SELECT status FROM letters WHERE id = 'letter-sign'`);
        expect(letter.rows[0].status).toBe('SIGNED');
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('a failed passphrase attempt cannot overwrite the sentinel with a short lockout', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      // Arm the sentinel first, then attempt a wrong passphrase. `assertCanSign`
      // refuses at the pre-flight, so nothing races; the point is that no write
      // performed by the failure path can replace the sentinel.
      await commitSuspensionLock();

      await expect(
        EsignService.signLetter('letter-sign', 'u-ketua', 'passphrase-yang-salah')
      ).rejects.toThrow();

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT locked_until, failed_attempts FROM user_signing_keys WHERE id = 'key-ketua'`
        );
        expect(
          new Date(key.rows[0].locked_until).toISOString(),
          'the sentinel must be untouched'
        ).toBe(new Date(SENTINEL).toISOString());
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('re-arms the short lockout after a previous lockout has expired', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      // An expired lockout is left in place (a successful signature is what
      // clears it). The failed-attempt write must still match and re-arm, or the
      // key would stay unlocked after the window and be guessable again.
      await withClient(targetUrl, async (db) => {
        await db.query(
          `UPDATE user_signing_keys
           SET failed_attempts = 5, locked_until = now() - interval '1 minute'
           WHERE id = 'key-ketua'`
        );
      });

      await expect(
        EsignService.signLetter('letter-sign', 'u-ketua', 'passphrase-yang-salah')
      ).rejects.toThrow();

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT locked_until, failed_attempts FROM user_signing_keys WHERE id = 'key-ketua'`
        );
        expect(key.rows[0].failed_attempts).toBe(6);
        expect(
          new Date(key.rows[0].locked_until).getTime(),
          'an expired lockout must be re-armed, not left in the past'
        ).toBeGreaterThan(Date.now());
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('changePassphrase succeeds for a key whose lockedUntil is NULL', async () => {
    // The predicate must accept `lockedUntil IS NULL`. A negated comparison
    // (`NOT (locked_until >= $1)`) is NULL in SQL when `locked_until` is NULL,
    // so it matched no row and an ordinary, unlocked key could never swap its
    // passphrase — the regression this covers.
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      await withClient(targetUrl, async (db) => {
        await db.query(
          `UPDATE user_signing_keys
           SET locked_until = NULL, failed_attempts = 3
           WHERE id = 'key-ketua'`
        );
      });

      await expect(
        EsignService.changePassphrase('u-ketua', PASS, ACCOUNT_PASSWORD, NEW_PASS)
      ).resolves.toBeTruthy();

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT locked_until, failed_attempts FROM user_signing_keys WHERE id = 'key-ketua'`
        );
        expect(key.rows[0].locked_until, 'the swap keeps the key unlocked').toBeNull();
        expect(key.rows[0].failed_attempts, 'a successful swap clears the counter').toBe(0);
      });

      // The new passphrase really is the live one: signing with it verifies.
      await expect(
        EsignService.signLetter('letter-sign', 'u-ketua', NEW_PASS)
      ).resolves.toBeTruthy();
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('changePassphrase is still refused while the suspension sentinel holds', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      await commitSuspensionLock();

      // The sentinel is refused. Depending on where the guard trips the message
      // is either the suspension refusal or the generic "locked" message, so
      // the decision asserted here is *refusal plus the sentinel surviving*,
      // not the wording.
      await expect(
        EsignService.changePassphrase('u-ketua', PASS, ACCOUNT_PASSWORD, NEW_PASS)
      ).rejects.toThrow();

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT locked_until FROM user_signing_keys WHERE id = 'key-ketua'`
        );
        expect(
          new Date(key.rows[0].locked_until).toISOString(),
          'the sentinel must survive the refused swap'
        ).toBe(new Date(SENTINEL).toISOString());
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  /**
   * Commit a real board suspension for `u-enroll`, exactly as
   * `BoardSuspensionService` ends up doing: user switched off (writer token)
   * and an ACTIVE `BoardMemberSuspension`.
   */
  async function commitSuspensionForEnroll(): Promise<void> {
    await withClient(targetUrl, async (db) => {
      await db.query(`UPDATE users SET is_active = false WHERE id = 'u-enroll'`);
      await db.query(`
        INSERT INTO board_member_suspensions
          (id, user_id, sk_number, audit_reason, status, suspended_by_id, updated_at)
        VALUES
          ('susp-enroll', 'u-enroll', 'SK/ENROLL/1', 'Pembekuan uji aktivasi.', 'ACTIVE',
           'u-pengawas', now())
        ON CONFLICT (id) DO UPDATE SET status = 'ACTIVE'
      `);
    });
  }

  it('activation started before a suspension but writing after it leaves no unlocked key', async () => {
    await resetState();
    const { EsignService, prisma, previousUrl } = await loadModules();
    try {
      // The pre-flight approval read passes, then the suspension commits — the
      // exact interleaving the old read-then-write lacked. Because activation
      // re-checks under the user row lock, and it blocks on the same row a
      // suspension writes, whichever commits first is visible to the other.
      const original = prisma.signingKeyRequest.findFirst.bind(prisma.signingKeyRequest);
      let first = true;
      vi.spyOn(prisma.signingKeyRequest, 'findFirst').mockImplementation((async (args: any) => {
        const result = await original(args);
        if (first) {
          first = false;
          await commitSuspensionForEnroll();
        }
        return result;
      }) as any);

      await expect(EsignService.activateKey('u-enroll', PASS)).rejects.toThrow(
        /dibekukan|Pembekuan|non-aktif/i
      );

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT count(*)::int AS n FROM user_signing_keys WHERE user_id = 'u-enroll'`
        );
        expect(
          key.rows[0].n,
          'no unlocked signing key may be born for a just-suspended officer'
        ).toBe(0);
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('a suspension that commits first refuses activation outright', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      await commitSuspensionForEnroll();

      await expect(EsignService.activateKey('u-enroll', PASS)).rejects.toThrow(
        /dibekukan|Pembekuan|non-aktif/i
      );

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT count(*)::int AS n FROM user_signing_keys WHERE user_id = 'u-enroll'`
        );
        expect(key.rows[0].n).toBe(0);
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('normal activation with no suspension still succeeds', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      const out = await EsignService.activateKey('u-enroll', PASS);
      expect(out.id).toBeTruthy();

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT user_id, locked_until FROM user_signing_keys WHERE user_id = 'u-enroll'`
        );
        expect(key.rows).toHaveLength(1);
        expect(key.rows[0].locked_until).toBeNull();
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('an internal direct service call cannot bypass the suspension guard', async () => {
    // No route, no middleware: the check lives in the transaction, so calling
    // the service directly is still refused.
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      await commitSuspensionForEnroll();

      await expect(EsignService.activateKey('u-enroll', PASS)).rejects.toThrow(
        /dibekukan|Pembekuan|non-aktif/i
      );

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT count(*)::int AS n FROM user_signing_keys WHERE user_id = 'u-enroll'`
        );
        expect(key.rows[0].n).toBe(0);
      });
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('activation refuses a soft-deleted or inactive account', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    try {
      await withClient(targetUrl, async (db) => {
        await db.query(`UPDATE users SET is_active = false WHERE id = 'u-enroll'`);
      });
      await expect(EsignService.activateKey('u-enroll', PASS)).rejects.toThrow();

      await withClient(targetUrl, async (db) => {
        await db.query(
          `UPDATE users SET is_active = true, deleted_at = now() WHERE id = 'u-enroll'`
        );
      });
      await expect(EsignService.activateKey('u-enroll', PASS)).rejects.toThrow();
    } finally {
      await unloadModules(previousUrl);
    }
  });

  it('no deadlock when activation and suspension interleave on the user row', async () => {
    await resetState();
    const { EsignService, previousUrl } = await loadModules();
    const blocker = new Client({ connectionString: targetUrl });
    await blocker.connect();
    try {
      // A suspension holds the user row lock and commits the sentinel state;
      // activation must wait, then fail closed — not deadlock.
      await blocker.query('BEGIN');
      await blocker.query(`SELECT id FROM "users" WHERE id = 'u-enroll' FOR UPDATE`);
      await blocker.query(`UPDATE users SET is_active = false WHERE id = 'u-enroll'`);
      await blocker.query(`
        INSERT INTO board_member_suspensions
          (id, user_id, sk_number, audit_reason, status, suspended_by_id, updated_at)
        VALUES
          ('susp-enroll', 'u-enroll', 'SK/ENROLL/1', 'Pembekuan uji aktivasi.', 'ACTIVE',
           'u-pengawas', now())
        ON CONFLICT (id) DO UPDATE SET status = 'ACTIVE'
      `);

      const pending = EsignService.activateKey('u-enroll', PASS);
      await new Promise((resolve) => setTimeout(resolve, 400));
      await blocker.query('COMMIT');

      await expect(pending).rejects.toThrow(/dibekukan|Pembekuan|non-aktif/i);

      await withClient(targetUrl, async (db) => {
        const key = await db.query(
          `SELECT count(*)::int AS n FROM user_signing_keys WHERE user_id = 'u-enroll'`
        );
        expect(key.rows[0].n).toBe(0);
      });
    } finally {
      await blocker.end();
      await unloadModules(previousUrl);
    }
  });
});
