import { prisma } from '@/lib/prisma';
import { Prisma } from '@prisma/client';
import { ApiError, ErrorCode } from '@/middleware/error';
import { CreateSimaanInput, UpdateSimaanResultInput, ListSimaanQuery } from './takhosus.schema';

/**
 * Shared helper to revert side-effects when a passed simaan exam is invalidated
 * (either re-graded to failed or deleted). Must be called within a Prisma transaction.
 */
async function revertSimaanSideEffects(
  tx: Prisma.TransactionClient,
  exam: { id: string; studentId: string; juzStart: number; juzEnd: number },
  enrollment: {
    id: string;
    studentId: string;
    status: string;
    currentJuz: number;
    targetJuz: number;
    completedJuz: number;
    completedAt: Date | null;
  },
  /** When reverting a delete, the exam is already gone — skip the `id: { not: exam.id }` filter */
  examAlreadyDeleted = false
) {
  const idFilter = examAlreadyDeleted ? {} : { id: { not: exam.id } };

  if (exam.juzEnd === 30 && exam.juzStart === 1) {
    // Check if another passed 30-juz exam exists for this student
    const otherPassed30JuzExam = await tx.simaanExam.findFirst({
      where: {
        studentId: exam.studentId,
        ...idFilter,
        passed: true,
        juzStart: 1,
        juzEnd: 30,
      },
      select: { id: true },
    });

    // Only revert if no other passed 30-juz exam justifies the completion
    if (!otherPassed30JuzExam) {
      const sanadCount = enrollment.id
        ? await tx.sanadRecord.count({ where: { enrollmentId: enrollment.id } })
        : 0;
      const sanadJustifiesCompletion = sanadCount >= enrollment.targetJuz;

      // Re-read enrollment status inside the transaction to avoid stale snapshot
      const freshEnrollment = await tx.takhosusEnrollment.findUnique({
        where: { studentId: exam.studentId },
        select: { status: true },
      });
      const currentStatus = freshEnrollment?.status ?? enrollment.status;

      if (currentStatus === 'COMPLETED' && !sanadJustifiesCompletion) {
        // Derive the correct currentJuz from other passed simaan exams
        const otherPassedExams = await tx.simaanExam.findMany({
          where: {
            studentId: exam.studentId,
            ...idFilter,
            passed: true,
          },
          select: { juzEnd: true },
          orderBy: { juzEnd: 'desc' },
          take: 1,
        });
        const derivedCurrentJuz =
          otherPassedExams.length > 0 ? Math.min(30, otherPassedExams[0].juzEnd + 1) : 1;

        // Only clear notes if they were auto-generated by simaan completion.
        // Preserve manually-edited notes to avoid data loss.
        const currentEnrollment = await tx.takhosusEnrollment.findUnique({
          where: { studentId: exam.studentId },
          select: { notes: true },
        });
        const isAutoGeneratedNote = currentEnrollment?.notes?.startsWith(
          'Lulus Simaan 30 Juz pada '
        );

        await tx.takhosusEnrollment.update({
          where: { studentId: exam.studentId },
          data: {
            status: 'ACTIVE',
            completedAt: null,
            currentJuz: derivedCurrentJuz,
            completedJuz: sanadCount,
            ...(isAutoGeneratedNote && { notes: null }),
          },
        });
      }

      // Remove Hafidz record only if no other 30-juz pass AND sanad records don't justify it
      if (!sanadJustifiesCompletion) {
        await tx.hafidzStudent.deleteMany({
          where: { studentId: exam.studentId },
        });
      }
    }
  } else {
    // Re-read currentJuz to avoid stale snapshot
    const freshEnrollmentForJuz = await tx.takhosusEnrollment.findUnique({
      where: { studentId: exam.studentId },
      select: { currentJuz: true },
    });
    const currentJuz = freshEnrollmentForJuz?.currentJuz ?? enrollment.currentJuz ?? 0;

    if (currentJuz === Math.min(30, exam.juzEnd + 1)) {
      // Revert currentJuz bump: derive correct value from remaining passed exams
      // Only revert if the enrollment's currentJuz was likely set by this exam
      const otherPassedExams = await tx.simaanExam.findMany({
        where: {
          studentId: exam.studentId,
          ...idFilter,
          passed: true,
        },
        select: { juzEnd: true },
        orderBy: { juzEnd: 'desc' },
        take: 1,
      });
      const derivedCurrentJuz =
        otherPassedExams.length > 0 ? Math.min(30, otherPassedExams[0].juzEnd + 1) : 1;

      await tx.takhosusEnrollment.update({
        where: { studentId: exam.studentId },
        data: { currentJuz: derivedCurrentJuz },
      });
    }
  }
}

export const simaanService = {
  async create(data: CreateSimaanInput, creatorId: string) {
    // Verify student exists
    const student = await prisma.student.findUnique({
      where: { id: data.studentId },
      include: { takhosusEnrollment: true },
    });

    if (!student) {
      throw new ApiError(ErrorCode.NOT_FOUND, 'Student not found');
    }

    // Create simaan exam
    return prisma.simaanExam.create({
      data: {
        studentId: data.studentId,
        enrollmentId: student.takhosusEnrollment?.id,
        // @ts-ignore - Prisma enum mismatch workaroud or raw string
        simaanType: data.simaanType as any,
        examDate: new Date(data.examDate),
        juzStart: data.juzStart,
        juzEnd: data.juzEnd,
        // @ts-ignore
        duration: data.durationMinutes,
        notes: data.notes,
        examiners: {
          create: data.examinerIds.map((examinerId) => ({
            examinerId,
          })),
        },
      },
      include: {
        student: {
          include: { user: { select: { name: true } } },
        },
        examiners: {
          include: { examiner: { select: { id: true, name: true } } },
        },
      },
    });
  },

  async findAll(query: ListSimaanQuery) {
    const { page, limit, studentId, unitId, classId, startDate, endDate, status } = query;
    const skip = (page - 1) * limit;

    const where: Prisma.SimaanExamWhereInput = {
      ...(studentId && { studentId }),
      ...(unitId && { student: { unitId } }),
      ...(classId && { student: { enrollments: { some: { classId, status: 'active' } } } }),
      ...(startDate &&
        endDate && {
          examDate: {
            gte: new Date(startDate),
            lte: new Date(endDate),
          },
        }),
      // @ts-ignore
      ...(status && { status }), // Note: status field might be string in schema but inferred as enum in Prisma types
    };

    const [exams, total] = await Promise.all([
      prisma.simaanExam.findMany({
        where,
        skip,
        take: limit,
        orderBy: { examDate: 'desc' },
        include: {
          student: {
            include: { user: { select: { name: true } } },
          },
          examiners: {
            include: { examiner: { select: { id: true, name: true } } },
          },
          _count: {
            select: { examiners: true },
          },
        },
      }),
      prisma.simaanExam.count({ where }),
    ]);

    return {
      exams,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    };
  },

  async findById(id: string) {
    const exam = await prisma.simaanExam.findUnique({
      where: { id },
      include: {
        student: {
          include: {
            user: { select: { name: true } },
            takhosusEnrollment: true,
          },
        },
        examiners: {
          include: { examiner: { select: { id: true, name: true } } },
        },
      },
    });

    if (!exam) {
      throw new ApiError(ErrorCode.NOT_FOUND, 'Simaan exam not found');
    }

    return exam;
  },

  async updateResult(id: string, data: UpdateSimaanResultInput) {
    // Defensive: ensure `passed` is an explicit boolean before running side-effects.
    // The Zod schema enforces `z.boolean()` today, but if it ever becomes optional,
    // an undefined value would silently skip the pass branch while the status write
    // (line below) would set 'FAILED'. This guard makes the contract explicit.
    if (typeof data.passed !== 'boolean') {
      throw new ApiError(ErrorCode.BAD_REQUEST, 'passed must be a boolean');
    }

    const updatedExam = await prisma.$transaction(async (tx) => {
      // Re-read inside transaction for a consistent snapshot of enrollment data
      const exam = await tx.simaanExam.findUnique({
        where: { id },
        include: { student: { include: { takhosusEnrollment: true } } },
      });
      if (!exam) {
        throw new ApiError(ErrorCode.NOT_FOUND, 'Simaan exam not found');
      }

      const result = await tx.simaanExam.update({
        where: { id },
        data: {
          overallScore: data.overallScore,
          tajwidScore: data.tajwidScore,
          fashohaScore: data.fashohaScore,
          tartilScore: data.tartilScore,
          grade: data.grade,
          passed: data.passed,
          notes: data.notes,
          recommendations: data.recommendations,
          // @ts-ignore
          status: data.passed === true ? 'PASSED' : 'FAILED',
        },
      });

      if (data.passed === true && exam.passed === false && exam.student.takhosusEnrollment) {
        // Re-read enrollment inside the transaction for a consistent snapshot,
        // matching the revert path which also re-reads (see revertSimaanSideEffects).
        // Without this, a concurrent sanad operation could auto-complete the enrollment
        // between the exam read (line 249) and the status check below, causing us to
        // overwrite completedAt/notes or regress currentJuz.
        const freshEnrollment = await tx.takhosusEnrollment.findUnique({
          where: { studentId: exam.studentId },
        });
        if (!freshEnrollment) {
          // Enrollment was deleted concurrently — skip side-effects
          return result;
        }

        // 1. Level-up trigger: If passed 30 juz simaan, mark enrollment as COMPLETED and eligible for certificate
        if (exam.juzEnd === 30 && exam.juzStart === 1) {
          // Only update enrollment if not already COMPLETED (e.g., by sanad auto-completion)
          // to avoid overwriting existing completedAt/notes metadata
          if (freshEnrollment.status !== 'COMPLETED') {
            await tx.takhosusEnrollment.update({
              where: { studentId: exam.studentId },
              data: {
                status: 'COMPLETED',
                completedAt: new Date(),
                currentJuz: 30,
                completedJuz: freshEnrollment.targetJuz,
                notes: `Lulus Simaan 30 Juz pada ${new Date().toLocaleDateString()}`,
              },
            });
          }

          // 2. Auto-record Hafidz status (preserve existing completedAt if already recorded)
          const existingHafidz = await tx.hafidzStudent.findUnique({
            where: { studentId: exam.studentId },
            select: { id: true },
          });
          if (!existingHafidz) {
            await tx.hafidzStudent.create({
              data: {
                studentId: exam.studentId,
                completedAt: new Date(),
                notes: 'Lulus program Takhosus',
              },
            });
          }
        } else {
          // 3. Update current juz progress in enrollment if passed a contiguous juz simaan.
          //    Both guards are required to ensure strict contiguous progression:
          //    - juzStart <= currentJuz: the simaan starts at or before the student's
          //      current position (covers their frontier)
          //    - juzEnd < currentJuz is skipped: only advance, never regress
          //    - juzStart must be adjacent: the gap between currentJuz and juzStart
          //      must be zero (exact match) or the simaan must overlap currentJuz.
          //    This prevents non-sequential exams (e.g., juz 20-25 when currentJuz=5)
          //    from skipping intermediate juz.
          const currentJuz = freshEnrollment.currentJuz || 1;
          const coversCurrentPosition = exam.juzStart <= currentJuz && exam.juzEnd >= currentJuz;
          if (coversCurrentPosition) {
            await tx.takhosusEnrollment.update({
              where: { studentId: exam.studentId },
              data: { currentJuz: Math.min(30, exam.juzEnd + 1) },
            });
          }
        }
      } else if (data.passed === false && exam.passed === true && exam.student.takhosusEnrollment) {
        // Revert side-effects when re-grading from passed to failed
        await revertSimaanSideEffects(tx, exam, exam.student.takhosusEnrollment);
      }

      return result;
    });

    return updatedExam;
  },

  async delete(id: string) {
    await prisma.$transaction(async (tx) => {
      const exam = await tx.simaanExam.findUnique({
        where: { id },
        include: { student: { include: { takhosusEnrollment: true } } },
      });
      if (!exam) {
        throw new ApiError(ErrorCode.NOT_FOUND, 'Simaan exam not found');
      }

      await tx.simaanExam.delete({ where: { id } });

      // Revert side-effects if the deleted exam was passed
      if (exam.passed && exam.student.takhosusEnrollment) {
        // examAlreadyDeleted=true so the helper won't filter by `id: { not: exam.id }`
        await revertSimaanSideEffects(tx, exam, exam.student.takhosusEnrollment, true);
      }
    });

    return { success: true };
  },
};
