/**
 * Canonical demo accounts — at least one per RoleCode in the system. MUSYRIF
 * and MUHAFIDZ have several personas (putra/putri, wali kamar, murabbi) since
 * those roles were merged on 2026-09-25; the seed looks a role up by its FIRST
 * account.
 *
 * This single list is the source of truth for the API seed
 * (apps/api/prisma/seed.ts), which creates the login users, and for the tools
 * that log in as them (the e2e suite, scripts/screenshot-roles.ts). Edit
 * accounts here, never in the consumers. The login page no longer lists them:
 * the demo credential panel was removed with DEMO_MODE (2026-09-23).
 *
 * Real names + photos are used for the six leaders of Yayasan Pesantren
 * Cipansor. All other names are representative demo data.
 */

export interface DemoAccount {
  /** Realm the account belongs to (YAYASAN, PESANTREN, SD_IT, …). */
  group: string;
  /** Must match the Prisma RoleCode enum exactly. */
  roleCode: string;
  name: string;
  email: string;
  password: string;
  description: string;
  /** Public path to an avatar, when a real photo exists. */
  photo?: string;
}

/** Every seeded demo account shares one password. */
export const DEMO_PASSWORD = "Cipansor123!";

const P = DEMO_PASSWORD;

export const DEMO_ACCOUNTS: DemoAccount[] = [
  // ── Global & Yayasan ────────────────────────────────────────────────
  {
    group: "YAYASAN",
    roleCode: "SUPER_ADMIN",
    name: "Administrator Sistem",
    email: "super.admin@cipansor.or.id",
    password: P,
    description: "Akses penuh seluruh sistem",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_KETUA",
    name: "H. Ramram Mansur Ramdani, S.Pd.I., M.Ag",
    email: "yayasan.ketua@cipansor.or.id",
    password: P,
    description: "Ketua Yayasan Pesantren Cipansor",
    photo: "/images/people/ketua-yayasan.webp",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_PEMBINA",
    name: "K.H. Endang Saepudin, M.Pd.I",
    email: "yayasan.pembina@cipansor.or.id",
    password: P,
    description: "Pembina Yayasan",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_PENGAWAS",
    name: "H. Ujang Suryana, S.E.",
    email: "yayasan.pengawas@cipansor.or.id",
    password: P,
    description: "Pengawas Yayasan",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_SEKRETARIS",
    name: "Hj. Siti Maemunah, S.Pd.",
    email: "yayasan.sekretaris@cipansor.or.id",
    password: P,
    description: "Sekretaris Yayasan",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_BENDAHARA",
    name: "H. Andi Muhammad Badrudin, S.T.",
    email: "yayasan.bendahara@cipansor.or.id",
    password: P,
    description: "Bendahara Yayasan",
    photo: "/images/people/bendahara-yayasan.webp",
  },
  {
    group: "YAYASAN",
    roleCode: "YAYASAN_ANGGOTA",
    name: "H. Dedi Mulyadi, S.Ag.",
    email: "yayasan.anggota@cipansor.or.id",
    password: P,
    description: "Anggota Pengurus Yayasan",
  },

  // ── Pesantren ───────────────────────────────────────────────────────
  {
    group: "PESANTREN",
    roleCode: "PESANTREN_PENGASUH",
    name: "K.H. Muhammad Taufik Ismail, S.Pd",
    email: "pesantren.pengasuh@cipansor.or.id",
    password: P,
    description: "Pimpinan Pesantren (Kiai), juga Pembina yayasan",
    photo: "/images/people/pimpinan-pesantren.webp",
  },
  {
    group: "PESANTREN",
    roleCode: "PESANTREN_TATA_USAHA",
    name: "Ahmad Ridwan, S.Kom.",
    email: "pesantren.tu@cipansor.or.id",
    password: P,
    description: "Tata Usaha Pesantren",
  },
  {
    group: "PESANTREN",
    roleCode: "USTADZ",
    name: "Ustadz Abdul Karim, Lc.",
    email: "pesantren.ustadz@cipansor.or.id",
    password: P,
    description: "Ustadz pengampu kitab",
  },
  {
    group: "PESANTREN",
    roleCode: "MUSYRIF",
    name: "Ustadz Fahmi Nurhidayat",
    email: "pesantren.musyrif@cipansor.or.id",
    password: P,
    description: "Pembina asrama putra",
  },
  {
    group: "PESANTREN",
    roleCode: "MUSYRIF",
    name: "Ustadzah Nur Aisyah",
    email: "pesantren.musyrifah@cipansor.or.id",
    password: P,
    description: "Pembina asrama putri",
  },
  {
    group: "PESANTREN",
    roleCode: "MUHAFIDZ",
    name: "Ustadz Hafizh Anwar, Al-Hafidz",
    email: "pesantren.muhafidz@cipansor.or.id",
    password: P,
    description: "Pengampu tahfidz putra",
  },
  {
    group: "PESANTREN",
    roleCode: "MUHAFIDZ",
    name: "Ustadzah Khodijah, Al-Hafidzah",
    email: "pesantren.muhafidzah@cipansor.or.id",
    password: P,
    description: "Pengampu tahfidz putri",
  },
  {
    group: "PESANTREN",
    roleCode: "MUSYRIF",
    name: "Ustadz Salman Alfarisi",
    email: "pesantren.murabbi@cipansor.or.id",
    password: P,
    description: "Musyrif — pembina akhlak (murabbi)",
  },
  {
    group: "PESANTREN",
    roleCode: "MUSYRIF",
    name: "Ustadz Rizki Ramadhan",
    email: "pesantren.walikamar@cipansor.or.id",
    password: P,
    description: "Musyrif — wali kamar",
  },

  // ── TK Qur'an ───────────────────────────────────────────────────────
  {
    group: "TK_QURAN",
    roleCode: "TKQ_ADMIN",
    name: "Admin TK Qur'an",
    email: "tkq.admin@cipansor.or.id",
    password: P,
    description: "Administrator TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_KEPALA_SEKOLAH",
    name: "Hj. Wulan Sari, S.Pd.AUD",
    email: "tkq.kepala@cipansor.or.id",
    password: P,
    description: "Kepala TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_WAKASEK",
    name: "Rina Marlina, S.Pd.",
    email: "tkq.wakasek@cipansor.or.id",
    password: P,
    description: "Wakil Kepala TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_GURU",
    name: "Bunda Fitri Handayani, S.Pd.",
    email: "tkq.guru@cipansor.or.id",
    password: P,
    description: "Guru TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_WALI_KELAS",
    name: "Bunda Neng Sartika, S.Pd.",
    email: "tkq.walikelas@cipansor.or.id",
    password: P,
    description: "Wali Kelas TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_TATA_USAHA",
    name: "Dewi Puspitasari",
    email: "tkq.tu@cipansor.or.id",
    password: P,
    description: "Tata Usaha TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_BENDAHARA",
    name: "Euis Komariah",
    email: "tkq.bendahara@cipansor.or.id",
    password: P,
    description: "Bendahara TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_KOMITE",
    name: "H. Asep Saepuloh",
    email: "tkq.komite@cipansor.or.id",
    password: P,
    description: "Komite TK Qur'an",
  },
  {
    group: "TK_QURAN",
    roleCode: "TKQ_ORANG_TUA",
    name: "Ibu Yeni Rahayu",
    email: "tkq.ortu@cipansor.or.id",
    password: P,
    description: "Orang tua santri TK Qur'an",
  },

  // ── SD IT ───────────────────────────────────────────────────────────
  {
    group: "SD_IT",
    roleCode: "SDIT_ADMIN",
    name: "Admin SD IT",
    email: "sdit.admin@cipansor.or.id",
    password: P,
    description: "Administrator SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_KEPALA_SEKOLAH",
    name: "H. Dadan Ali Ridwan, S.Ag",
    email: "sdit.kepala@cipansor.or.id",
    password: P,
    description: "Kepala SD IT",
    photo: "/images/people/kepala-sdit.webp",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_WAKASEK",
    name: "Agus Setiawan, S.Pd.",
    email: "sdit.wakasek@cipansor.or.id",
    password: P,
    description: "Wakil Kepala SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_GURU",
    name: "Ustadz Yusuf Maulana, S.Pd.",
    email: "sdit.guru@cipansor.or.id",
    password: P,
    description: "Guru SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_WALI_KELAS",
    name: "Ustadzah Siti Nurjanah, S.Pd.",
    email: "sdit.walikelas@cipansor.or.id",
    password: P,
    description: "Wali Kelas SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_TATA_USAHA",
    name: "Iwan Setiadi",
    email: "sdit.tu@cipansor.or.id",
    password: P,
    description: "Tata Usaha SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_BENDAHARA",
    name: "Nia Kurniasih",
    email: "sdit.bendahara@cipansor.or.id",
    password: P,
    description: "Bendahara SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_KOMITE",
    name: "H. Deden Supriadi",
    email: "sdit.komite@cipansor.or.id",
    password: P,
    description: "Komite SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_ORANG_TUA",
    name: "Bapak Hendra Gunawan",
    email: "sdit.ortu@cipansor.or.id",
    password: P,
    description: "Orang tua santri SD IT",
  },
  {
    group: "SD_IT",
    roleCode: "SDIT_SISWA",
    name: "Ananda Muhammad Fauzan",
    email: "sdit.siswa@cipansor.or.id",
    password: P,
    description: "Santri SD IT",
  },

  // ── SMP IT ──────────────────────────────────────────────────────────
  {
    group: "SMP_IT",
    roleCode: "SMPIT_ADMIN",
    name: "Admin SMP IT",
    email: "smpit.admin@cipansor.or.id",
    password: P,
    description: "Administrator SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_KEPALA_SEKOLAH",
    name: "H. Cecep Helmi Syawali, Lc., M.Ag",
    email: "smpit.kepala@cipansor.or.id",
    password: P,
    description: "Kepala SMP IT",
    photo: "/images/people/kepala-smpit.webp",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_WAKASEK",
    name: "Dodi Hermawan, S.Pd.",
    email: "smpit.wakasek@cipansor.or.id",
    password: P,
    description: "Wakil Kepala SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_GURU",
    name: "Ustadz Ahmad Musyaffa, S.Pd.",
    email: "smpit.guru@cipansor.or.id",
    password: P,
    description: "Guru SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_WALI_KELAS",
    name: "Ustadzah Fatimah Zahra, S.Pd.",
    email: "smpit.walikelas@cipansor.or.id",
    password: P,
    description: "Wali Kelas SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_GURU_BK",
    name: "Sri Wahyuni, S.Psi.",
    email: "smpit.bk@cipansor.or.id",
    password: P,
    description: "Guru BK SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_TATA_USAHA",
    name: "Bambang Sutrisno",
    email: "smpit.tu@cipansor.or.id",
    password: P,
    description: "Tata Usaha SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_BENDAHARA",
    name: "Ratna Sari",
    email: "smpit.bendahara@cipansor.or.id",
    password: P,
    description: "Bendahara SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_KOMITE",
    name: "H. Tatang Suherman",
    email: "smpit.komite@cipansor.or.id",
    password: P,
    description: "Komite SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_ORANG_TUA",
    name: "Bapak Slamet Riyadi",
    email: "smpit.ortu@cipansor.or.id",
    password: P,
    description: "Orang tua santri SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_SISWA",
    name: "Ananda Rayhan Al-Ghifari",
    email: "smpit.siswa@cipansor.or.id",
    password: P,
    description: "Santri SMP IT",
  },
  {
    group: "SMP_IT",
    roleCode: "SMPIT_ALUMNI",
    name: "Fikri Haikal",
    email: "smpit.alumni@cipansor.or.id",
    password: P,
    description: "Alumni SMP IT",
  },

  // ── SMA Qur'an ──────────────────────────────────────────────────────
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_ADMIN",
    name: "Admin SMA Qur'an",
    email: "smaq.admin@cipansor.or.id",
    password: P,
    description: "Administrator SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_KEPALA_SEKOLAH",
    name: "H.M. Rizkon Hakiki, Lc., Al-Hafidz",
    email: "smaq.kepala@cipansor.or.id",
    password: P,
    description: "Kepala SMA Qur'an",
    photo: "/images/people/kepala-smaquran.webp",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_WAKASEK",
    name: "Taufik Hidayat, S.Pd.",
    email: "smaq.wakasek@cipansor.or.id",
    password: P,
    description: "Wakil Kepala SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_GURU",
    name: "Ustadz Malik Ibrahim, Lc.",
    email: "smaq.guru@cipansor.or.id",
    password: P,
    description: "Guru SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_WALI_KELAS",
    name: "Ustadzah Halimah Sa'diyah, S.Pd.",
    email: "smaq.walikelas@cipansor.or.id",
    password: P,
    description: "Wali Kelas SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_GURU_BK",
    name: "Anisa Rahmawati, S.Psi.",
    email: "smaq.bk@cipansor.or.id",
    password: P,
    description: "Guru BK SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_TATA_USAHA",
    name: "Hendi Kurnia",
    email: "smaq.tu@cipansor.or.id",
    password: P,
    description: "Tata Usaha SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_BENDAHARA",
    name: "Wati Nurhayati",
    email: "smaq.bendahara@cipansor.or.id",
    password: P,
    description: "Bendahara SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_KOMITE",
    name: "H. Endang Rustandi",
    email: "smaq.komite@cipansor.or.id",
    password: P,
    description: "Komite SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_ORANG_TUA",
    name: "Bapak Agus Salim",
    email: "smaq.ortu@cipansor.or.id",
    password: P,
    description: "Orang tua santri SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_SISWA",
    name: "Ananda Zaidan Abdullah",
    email: "smaq.siswa@cipansor.or.id",
    password: P,
    description: "Santri SMA Qur'an",
  },
  {
    group: "SMA_QURAN",
    roleCode: "SMAQ_ALUMNI",
    name: "Arya Satria",
    email: "smaq.alumni@cipansor.or.id",
    password: P,
    description: "Alumni SMA Qur'an",
  },

  // ── Sarana & Unit Usaha ─────────────────────────────────────────────
  {
    group: "SARANA_USAHA",
    roleCode: "PUSTAKAWAN",
    name: "Lestari Ningsih, S.IP.",
    email: "sarana.pustakawan@cipansor.or.id",
    password: P,
    description: "Pustakawan / perpustakaan",
  },
  {
    group: "SARANA_USAHA",
    roleCode: "PERAWAT",
    name: "Ns. Dian Anggraini, S.Kep.",
    email: "sarana.perawat@cipansor.or.id",
    password: P,
    description: "Perawat UKS & klinik",
  },
  {
    group: "SARANA_USAHA",
    roleCode: "KEAMANAN",
    name: "Sukirman",
    email: "sarana.keamanan@cipansor.or.id",
    password: P,
    description: "Petugas keamanan",
  },
  {
    group: "SARANA_USAHA",
    roleCode: "LABORAN",
    name: "Eka Prasetyo, S.Si.",
    email: "sarana.laboran@cipansor.or.id",
    password: P,
    description: "Laboran & praktikum",
  },
  {
    group: "SARANA_USAHA",
    roleCode: "BUSINESS_MANAGER",
    name: "H. Rahmat Hidayat, S.E.",
    email: "usaha.manager@cipansor.or.id",
    password: P,
    description: "Manajer unit usaha",
  },
  {
    group: "SARANA_USAHA",
    roleCode: "BUSINESS_STAFF",
    name: "Yudi Setiawan",
    email: "usaha.staff@cipansor.or.id",
    password: P,
    description: "Staf unit usaha",
  },
];
