/**
 * Build a PR comment for the Playwright e2e run and post it.
 *
 * Replaces the daun/playwright-report-comment action so the comment can carry
 * the per-test screenshots (captured for every test — see playwright.config.ts
 * `screenshot: "on"`) split into "passed" and "failed" groups, plus links to
 * the uploaded artifacts.
 *
 * GitHub has no supported API to embed images inline in a comment (the
 * drag-and-drop web flow uses a signed upload that a CI token cannot reach), so
 * screenshots are listed by filename and referenced from the screenshots
 * artifact rather than rendered. The artifact is overwritten on every re-run of
 * the same PR, so it never accumulates.
 *
 * Requires env:
 *   GITHUB_TOKEN, GH_REPOSITORY (from ${{ github.repository }}),
 *   GH_EVENT_NAME (pull_request), PR_NUMBER,
 *   RESULT_JSON, SCREENSHOT_ARTIFACT_URL, REPORT_ARTIFACT_URL
 */

import fs from "node:fs";
import path from "node:path";

const REPO = process.env.GH_REPOSITORY ?? "";
const PR_NUMBER = process.env.PR_NUMBER ?? "";
const RESULT_JSON = process.env.RESULT_JSON ?? "apps/web/test-results/results.json";
const SCREENSHOT_ARTIFACT_URL = process.env.SCREENSHOT_ARTIFACT_URL ?? "";
const REPORT_ARTIFACT_URL = process.env.REPORT_ARTIFACT_URL ?? "";

if (!REPO || !PR_NUMBER) {
  // Not a pull_request run (e.g. push to main) — nothing to comment on. This is
  // a no-op, not a failure: the caller gates on github.event_name too.
  console.log("Skipping comment: missing GH_REPOSITORY or PR_NUMBER.");
  process.exit(0);
}

let report;
try {
  report = JSON.parse(fs.readFileSync(RESULT_JSON, "utf8"));
} catch {
  console.log(`Skipping comment: could not read report at ${RESULT_JSON}.`);
  process.exit(0);
}

// Playwright's JSON reporter nests TestCase objects under
// suites[].specs[].tests[] (not under suites[].tests — tests live inside a
// spec). We walk both shapes defensively so the parsing is robust to reporter
// version differences.
function collectTests(suites) {
  const tests = [];
  const walk = (list) => {
    for (const s of list) {
      if (Array.isArray(s.tests)) tests.push(...s.tests);
      if (Array.isArray(s.specs)) {
        for (const spec of s.specs) {
          if (Array.isArray(spec.tests)) tests.push(...spec.tests);
          if (Array.isArray(spec.suites)) walk(spec.suites);
        }
      }
      if (Array.isArray(s.suites)) walk(s.suites);
    }
  };
  walk(suites ?? []);
  return tests;
}

const tests = collectTests(report.suites);

const summary = {
  passed: 0,
  failed: 0,
  skipped: 0,
  other: 0,
};

// { title -> [artifact-relative screenshot paths] }
const passedScreens = new Map();
const failedScreens = new Map();

function relScreenshotPath(absPath) {
  return path.relative("apps/web/test-results", absPath).split(path.sep).join("/");
}

for (const test of tests) {
  const status = test.status ?? test.results?.[test.results.length - 1]?.status ?? "unknown";
  summary[status] = (summary[status] ?? 0) + 1;

  const shots = [];
  for (const result of test.results ?? []) {
    for (const att of result.attachments ?? []) {
      if (att.contentType?.startsWith("image/") && att.path && fs.existsSync(att.path)) {
        shots.push(relScreenshotPath(att.path));
      }
    }
  }
  if (!shots.length) continue;

  const bucket = status === "passed" ? passedScreens : status === "failed" ? failedScreens : null;
  if (bucket) bucket.set(test.title, shots);
}

const mkSection = (heading, map) => {
  if (map.size === 0) {
    return `<details><summary>${heading} _(0)_</summary>\n\n_No screenshots._\n</details>\n`;
  }
  const lines = [`<details open><summary>${heading} _(${map.size} test${map.size === 1 ? "" : "s"})_</summary>\n`];
  for (const [title, shots] of map) {
    lines.push(`\n**${title}**`);
    for (const s of shots) lines.push(`- \`${s}\``);
  }
  lines.push("\n</details>\n");
  return lines.join("\n");
};

const body = [
  `## Playwright E2E Screenshots (PR #${PR_NUMBER})`,
  "",
  `**Summary:** ${summary.passed} passed · ${summary.failed} failed · ${summary.skipped} skipped${summary.other ? ` · ${summary.other} other` : ""}`,
  "",
  mkSection("✅ Screenshots from passing tests", passedScreens),
  "",
  mkSection("❌ Screenshots from failing tests", failedScreens),
  "",
  `> Screenshot files are grouped by test. Download the [screenshots artifact](${SCREENSHOT_ARTIFACT_URL || "_(upload skipped)_"}) for the actual files. ${REPORT_ARTIFACT_URL ? `Full [Playwright report](${REPORT_ARTIFACT_URL}).` : ""}`,
  "",
  "<sub>Comment generated by an AI agent (OpenHands) on behalf of the Cipansor workflow.</sub>",
].join("\n");

const url = `https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments`;
const res = await fetch(url, {
  method: "POST",
  headers: {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN ?? ""}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({ body }),
});

if (!res.ok) {
  const err = await res.text();
  console.error(`Failed to post comment (HTTP ${res.status}): ${err.slice(0, 500)}`);
  process.exit(0); // cosmetic comment — never fail the gate
}
console.log(`Comment posted: ${res.status}`);
